version: '3.8'

services:
  app:
    image: my-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

    networks:
      - nginx-network

networks:
  nginx-network:
    external: true